### ISSUE TITLE
[FR] Bubble backend for coupon mechanism

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#210]
This is an issue for logging activities related to Bubble backend.

* API list: https://mylog-backend.bubbleapps.io/version-test/api/1.1/meta/swagger.json

**Comment by shc261392** [comment]
Problems encountered:

1. Either `/login/` or `/obj/user/{UniqueID}` only returns the user's unique ID (e.g. `1592871930598x873964103117486500`), not the wallet address. Since the transaction requires the wallet address of sender/receiver the App couldn't get the necessary information to run a transaction. (need to have a way to get the user's `wallet_address`)

`/obj/user/{uniqueID}` returns this:

```
{
  "response": {
    "user_signed_up": true,
    "_id": "1592871930598x873964103117486500"
  }
}
```

2. After a new user is created (by `/signup/`), its `current_balance` has no default value. Therefore the transaction workflow cannot be triggered. (Should be defaulted to `20`)

3. After running a transaction, the receiver's current balance won't increase.

**Comment by wcchung** [comment]
@shc261392 James, 這個 FR 目前算是已完成嗎? 因為看到的 comment 還有 problems encountered.

**Comment by tammyyang** [comment]
According to @scott-dt , the mechanism works on Android. From FR point of view, this issue should be closed. The rest issues are already opened and scheduled in later milestones.
